import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, Connection, Keypair } from "@solana/web3.js";
import { createHash } from "crypto";
import * as fs from 'fs';
import * as os from 'os';
import bs58 from 'bs58';
// Path to IDL generated by anchor build
const IDL_PATH = "../target/idl/orin_identity.json";
const NETWORK = process.env.NETWORK || 'Localnet';
const RPC_ENDPOINT = NETWORK === 'Localnet' ? 'http://127.0.0.1:8899' : 'https://api.devnet.solana.com';

async function runSimulation() {
    console.log("🎮 ORIN Web2.5 Hybrid Simulator Started...\n");

    const idl = JSON.parse(fs.readFileSync(IDL_PATH, "utf8"));
    const connection = new Connection(RPC_ENDPOINT, "confirmed");

    // Load Local Solana Wallet (~/.config/solana/id.json)
    const secretKeyString = fs.readFileSync(os.homedir() + "/.config/solana/id.json", 'utf8');
    const secretKey = Uint8Array.from(JSON.parse(secretKeyString));
    const walletKeypair = Keypair.fromSecretKey(secretKey);
    const wallet = new anchor.Wallet(walletKeypair);
    const provider = new anchor.AnchorProvider(connection, wallet, {
        commitment: "confirmed"
    });
    anchor.setProvider(provider);

    // Hardcode Program ID from Phase 1
    const PROGRAM_ID = new PublicKey("FqtrHgdYTph1DSP9jDYD7xrKPrjSjCTtnw6fyKMmboYk");
    const program = new Program(idl as anchor.Idl, provider);

    // Create a unqiue email for this run
    const testEmail = `guest_${Math.floor(Date.now() / 1000)}@orin.network`;
    const emailHashBuffer = createHash("sha256").update(testEmail.toLowerCase().trim()).digest();
    console.log("testEmail", testEmail);
    // Derive PDA based on the integration spec
    const [guestPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("guest"), emailHashBuffer],
      PROGRAM_ID
    );

    console.log(`👤 Using Wallet: ${wallet.publicKey.toBase58()}`);
    console.log(`🔑 Derived Guest PDA: ${guestPda.toBase58()}`);

    console.log(`\n[1/3] 📝 Sending InitializeGuest TX to ${NETWORK}...`);
    const tx1 = await program.methods
      .initializeGuest(Array.from(emailHashBuffer), "Demo Private Guest")
      .accounts({
        guestProfile: guestPda,
        user: wallet.publicKey,
        systemProgram: anchor.web3.SystemProgram.programId,
      } as any)
      .rpc();
    console.log(`✅ Success! TX Hash: ${tx1}\n`);
    
    // Pause briefly to ensure sequential execution and distinct listener logs
    await new Promise(resolve => setTimeout(resolve, 3000));

    // Define the Sensitive Information that should NEVER touch Solana!
    const newPreferencesRaw = JSON.stringify({
      temp: 18.5,
      brightness: 100,
      light_color: "#A020F0", // Purple
      color_mode: "SLEEP"
    });

    console.log(`[2/3] 🌐 PRE-FLIGHT (Web2): Sending secure JSON to Off-Chain Backend Server...`);
    
    // Send standard HTTPS POST bypassing Blockspace
    const res = await fetch("http://127.0.0.1:3001/api/preferences", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: newPreferencesRaw
    });

    const offChainResponse = await res.json();
    console.log(`✅ Success! Backend cached payload with Identity Hash: ${offChainResponse.hash}\n`);

    // Only hash hits the Blockchain
    const onChainHashLogBuffer = createHash("sha256").update(newPreferencesRaw.trim()).digest();

    console.log(`[3/3] 🎛️ FINAL LOCK: Sending HASH-ONLY State Validation to ${NETWORK}...`);
    const tx2 = await program.methods
      .updatePreferences(Array.from(onChainHashLogBuffer))
      .accounts({
        guestProfile: guestPda,
        owner: wallet.publicKey,
      } as any)
      .rpc();
      
    console.log(`✅ Chain Validated! TX Hash: ${tx2}`);
    console.log("\n👀 Done! Switch over to your backend running `yarn start`.");
    console.log("You should see it cross-verify the HTTP cache with the Blockchain State!\n");
}

runSimulation().catch(console.error);
